name = "caramel"
uuid = "2da0b1eb-fc91-4147-942b-22ff62eb0368"
authors = ["kreikrei <kreitonstrs@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
